### ISSUE TITLE
Bot should only listen to @botname messages in public channels

### ISSUE THREAD

**Issue by mantebridts** [mantebridts/slack-update-status#16]
When the bot is added to a channels, he listens (and responds) to *all* messages. This is no good.

Update the bot so it only listens to messages directed to him/her.

**Comment by structief** [comment]
Fixed in `bot-location-status` ([Commit #f9b0df7](https://github.com/mantebridts/slack-update-status/commit/f9b0df71b2cbbe00135530fa3aaa6d20c40e3e68))
